name: Cypress Parallel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }} --reporter mochawesome --reporter-options reportDir=cypress/reports/html,overwrite=false,html=false,json=true

      - name: Merge test reports
        if: ${{ matrix.browser == 'chrome' }}  
        run: |
          npx mochawesome-merge cypress/reports/html/*.json > cypress/reports/html/merged-report.json
          npx marge cypress/reports/html/merged-report.json -f report -o cypress/reports/html

      - name: Upload report artifact
        if: ${{ matrix.browser == 'chrome' }}
        uses: actions/upload-artifact@main
        with:
          name: mochawesome-html-report
          path: cypress/reports/html
      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: cypress-screenshots
          path: cypress/screenshots  
